// Blocos pré-definidos para o editor — definidos fora do componente React
// para não serem recriados a cada render (evita memory leaks e crashes)

export const EDITOR_BLOCKS = [
  // ── Hero ──────────────────────────────────────────────────────────────────
  {
    id: 'hero-dark', label: 'Hero Escuro', category: '🦸 Hero',
    content: '<section style="background:#1a1a2e;padding:80px 40px;text-align:center;font-family:sans-serif"><h1 style="color:#fff;font-size:48px;font-weight:800;margin:0 0 16px">Título Principal</h1><p style="color:#94a3b8;font-size:18px;margin:0 0 32px;max-width:560px;margin-left:auto;margin-right:auto">Descrição do seu produto ou serviço que convence o visitante a agir.</p><a href="#" style="display:inline-block;background:#E8922A;color:#000;padding:16px 40px;border-radius:50px;font-weight:700;font-size:16px;text-decoration:none">Começar Agora</a></section>',
  },
  {
    id: 'hero-light', label: 'Hero Claro', category: '🦸 Hero',
    content: '<section style="padding:80px 40px;text-align:center;background:#fff;font-family:sans-serif"><p style="color:#E8922A;font-size:13px;font-weight:700;letter-spacing:2px;text-transform:uppercase;margin:0 0 12px">Bem-vindo</p><h1 style="color:#111;font-size:48px;font-weight:900;margin:0 0 20px">Sites que <span style="color:#E8922A">Convertem</span></h1><p style="color:#666;font-size:17px;max-width:520px;margin:0 auto 36px;line-height:1.7">Design moderno e foco total em trazer resultados reais para o seu negócio.</p><a href="#" style="display:inline-block;background:#111;color:#fff;padding:16px 40px;border-radius:50px;font-weight:700;text-decoration:none">Solicitar Orçamento</a></section>',
  },
  {
    id: 'hero-split', label: 'Hero com Imagem', category: '🦸 Hero',
    content: '<section style="display:flex;align-items:center;gap:40px;padding:60px 40px;background:#0f0f23;font-family:sans-serif;flex-wrap:wrap"><div style="flex:1;min-width:260px"><h1 style="color:#fff;font-size:40px;font-weight:800;margin:0 0 16px;line-height:1.2">Transforme Seu Negócio Digital</h1><p style="color:#94a3b8;font-size:16px;line-height:1.7;margin:0 0 28px">Soluções completas para empresas que querem crescer online.</p><a href="#" style="display:inline-block;background:#E8922A;color:#000;padding:14px 32px;border-radius:10px;font-weight:700;text-decoration:none">Ver Planos</a></div><div style="flex:1;min-width:260px;background:#1a1a3e;border-radius:16px;height:280px;display:flex;align-items:center;justify-content:center;color:#E8922A;font-size:13px">📷 Insira sua imagem aqui</div></section>',
  },

  // ── Serviços ──────────────────────────────────────────────────────────────
  {
    id: 'servicos-3', label: 'Serviços 3 Col', category: '📦 Serviços',
    content: '<section style="padding:60px 40px;background:#f8f9fa;font-family:sans-serif"><h2 style="text-align:center;color:#111;font-size:32px;font-weight:800;margin:0 0 40px">Nossos Serviços</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;max-width:900px;margin:0 auto"><div style="background:#fff;border-radius:14px;padding:28px 20px;text-align:center;box-shadow:0 2px 16px rgba(0,0,0,0.06)"><div style="font-size:36px;margin-bottom:12px">🎨</div><h3 style="color:#111;font-size:18px;font-weight:700;margin:0 0 10px">Design</h3><p style="color:#666;font-size:14px;line-height:1.6">Layouts modernos que encantam seus visitantes.</p></div><div style="background:#fff;border-radius:14px;padding:28px 20px;text-align:center;box-shadow:0 2px 16px rgba(0,0,0,0.06)"><div style="font-size:36px;margin-bottom:12px">⚡</div><h3 style="color:#111;font-size:18px;font-weight:700;margin:0 0 10px">Performance</h3><p style="color:#666;font-size:14px;line-height:1.6">Sites ultra-rápidos com carregamento otimizado.</p></div><div style="background:#fff;border-radius:14px;padding:28px 20px;text-align:center;box-shadow:0 2px 16px rgba(0,0,0,0.06)"><div style="font-size:36px;margin-bottom:12px">📱</div><h3 style="color:#111;font-size:18px;font-weight:700;margin:0 0 10px">Responsivo</h3><p style="color:#666;font-size:14px;line-height:1.6">Perfeito em qualquer dispositivo.</p></div></div></section>',
  },
  {
    id: 'servicos-icones', label: 'Serviços com Ícone', category: '📦 Serviços',
    content: '<section style="padding:60px 40px;background:#fff;font-family:sans-serif"><h2 style="text-align:center;color:#111;font-size:32px;font-weight:800;margin:0 0 40px">O que fazemos</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:28px;max-width:900px;margin:0 auto"><div style="display:flex;gap:14px"><div style="background:#E8922A22;border-radius:12px;width:48px;height:48px;display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0">🛒</div><div><h3 style="color:#111;font-size:16px;font-weight:700;margin:0 0 6px">E-commerce</h3><p style="color:#666;font-size:13px;line-height:1.6;margin:0">Lojas virtuais completas com meios de pagamento.</p></div></div><div style="display:flex;gap:14px"><div style="background:#E8922A22;border-radius:12px;width:48px;height:48px;display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0">📊</div><div><h3 style="color:#111;font-size:16px;font-weight:700;margin:0 0 6px">Marketing Digital</h3><p style="color:#666;font-size:13px;line-height:1.6;margin:0">SEO, tráfego pago e redes sociais.</p></div></div><div style="display:flex;gap:14px"><div style="background:#E8922A22;border-radius:12px;width:48px;height:48px;display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0">💬</div><div><h3 style="color:#111;font-size:16px;font-weight:700;margin:0 0 6px">Suporte 24/7</h3><p style="color:#666;font-size:13px;line-height:1.6;margin:0">Equipe sempre pronta para ajudar.</p></div></div><div style="display:flex;gap:14px"><div style="background:#E8922A22;border-radius:12px;width:48px;height:48px;display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0">🔒</div><div><h3 style="color:#111;font-size:16px;font-weight:700;margin:0 0 6px">Segurança</h3><p style="color:#666;font-size:13px;line-height:1.6;margin:0">SSL, backups e proteção total.</p></div></div></div></section>',
  },

  // ── Sobre ─────────────────────────────────────────────────────────────────
  {
    id: 'sobre', label: 'Sobre a Empresa', category: '👥 Sobre',
    content: '<section style="padding:60px 40px;background:#fff;font-family:sans-serif"><div style="max-width:860px;margin:0 auto;display:flex;gap:48px;align-items:center;flex-wrap:wrap"><div style="flex:1;min-width:240px;background:#f0f0f0;border-radius:14px;height:260px;display:flex;align-items:center;justify-content:center;color:#999">📷 Foto</div><div style="flex:1;min-width:240px"><p style="color:#E8922A;font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;margin:0 0 10px">Sobre Nós</p><h2 style="color:#111;font-size:32px;font-weight:800;margin:0 0 16px;line-height:1.2">Mais de 10 anos criando experiências digitais</h2><p style="color:#666;font-size:15px;line-height:1.7;margin:0 0 24px">Somos apaixonados por tecnologia e resultados. Nossa missão é transformar negócios com soluções digitais inovadoras.</p><div style="display:flex;gap:24px;margin-bottom:24px"><div style="text-align:center"><div style="color:#E8922A;font-size:28px;font-weight:800">500+</div><div style="color:#666;font-size:13px">Projetos</div></div><div style="text-align:center"><div style="color:#E8922A;font-size:28px;font-weight:800">98%</div><div style="color:#666;font-size:13px">Satisfação</div></div><div style="text-align:center"><div style="color:#E8922A;font-size:28px;font-weight:800">10+</div><div style="color:#666;font-size:13px">Anos</div></div></div></div></div></section>',
  },

  // ── Depoimentos ───────────────────────────────────────────────────────────
  {
    id: 'depoimentos', label: 'Depoimentos', category: '💬 Depoimentos',
    content: '<section style="padding:60px 40px;background:#f8f9fa;font-family:sans-serif"><h2 style="text-align:center;color:#111;font-size:32px;font-weight:800;margin:0 0 40px">O que dizem nossos clientes</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px;max-width:960px;margin:0 auto"><div style="background:#fff;border-radius:14px;padding:24px;border-left:4px solid #E8922A"><p style="color:#444;font-size:14px;line-height:1.7;margin:0 0 16px;font-style:italic">"O site novo triplicou nossas reservas. Incrível o trabalho da equipe!"</p><div style="display:flex;align-items:center;gap:10px"><div style="width:40px;height:40px;background:#E8922A;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#000;font-weight:700">M</div><div><div style="color:#111;font-weight:700;font-size:13px">Maria Silva</div><div style="color:#999;font-size:12px">Restaurante</div></div></div></div><div style="background:#fff;border-radius:14px;padding:24px;border-left:4px solid #E8922A"><p style="color:#444;font-size:14px;line-height:1.7;margin:0 0 16px;font-style:italic">"Presença digital profissional e resultados visíveis. Super recomendo!"</p><div style="display:flex;align-items:center;gap:10px"><div style="width:40px;height:40px;background:#E8922A;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#000;font-weight:700">C</div><div><div style="color:#111;font-weight:700;font-size:13px">Carlos Melo</div><div style="color:#999;font-size:12px">Médico</div></div></div></div><div style="background:#fff;border-radius:14px;padding:24px;border-left:4px solid #E8922A"><p style="color:#444;font-size:14px;line-height:1.7;margin:0 0 16px;font-style:italic">"Vendas online cresceram 200% depois do novo site. Fantástico!"</p><div style="display:flex;align-items:center;gap:10px"><div style="width:40px;height:40px;background:#E8922A;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#000;font-weight:700">L</div><div><div style="color:#111;font-weight:700;font-size:13px">Laura Porto</div><div style="color:#999;font-size:12px">Loja de roupas</div></div></div></div></div></section>',
  },

  // ── Preços ────────────────────────────────────────────────────────────────
  {
    id: 'precos', label: 'Planos e Preços', category: '💰 Preços',
    content: '<section style="padding:60px 40px;background:#f8f9fa;font-family:sans-serif"><h2 style="text-align:center;color:#111;font-size:32px;font-weight:800;margin:0 0 40px">Planos e Preços</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;max-width:860px;margin:0 auto"><div style="background:#fff;border-radius:14px;padding:28px 20px"><h3 style="color:#111;font-size:17px;font-weight:700;margin:0 0 8px">Básico</h3><div style="color:#E8922A;font-size:36px;font-weight:900;margin:0 0 16px">R$99<span style="font-size:14px;color:#999">/mês</span></div><div style="color:#555;font-size:13px;margin-bottom:8px">✓ 5 páginas</div><div style="color:#555;font-size:13px;margin-bottom:8px">✓ SSL gratuito</div><div style="color:#555;font-size:13px;margin-bottom:16px">✓ Suporte email</div><a href="#" style="display:block;text-align:center;background:#111;color:#fff;padding:12px;border-radius:10px;font-weight:600;text-decoration:none">Contratar</a></div><div style="background:#111;border-radius:14px;padding:28px 20px"><div style="background:#E8922A;color:#000;font-size:11px;font-weight:700;padding:3px 10px;border-radius:50px;display:inline-block;margin-bottom:12px">POPULAR</div><h3 style="color:#fff;font-size:17px;font-weight:700;margin:0 0 8px">Profissional</h3><div style="color:#E8922A;font-size:36px;font-weight:900;margin:0 0 16px">R$199<span style="font-size:14px;color:#666">/mês</span></div><div style="color:#ccc;font-size:13px;margin-bottom:8px">✓ Ilimitado</div><div style="color:#ccc;font-size:13px;margin-bottom:8px">✓ SSL + CDN</div><div style="color:#ccc;font-size:13px;margin-bottom:16px">✓ Suporte 24/7</div><a href="#" style="display:block;text-align:center;background:#E8922A;color:#000;padding:12px;border-radius:10px;font-weight:700;text-decoration:none">Contratar</a></div><div style="background:#fff;border-radius:14px;padding:28px 20px"><h3 style="color:#111;font-size:17px;font-weight:700;margin:0 0 8px">Enterprise</h3><div style="color:#E8922A;font-size:36px;font-weight:900;margin:0 0 16px">R$499<span style="font-size:14px;color:#999">/mês</span></div><div style="color:#555;font-size:13px;margin-bottom:8px">✓ Tudo do Pro</div><div style="color:#555;font-size:13px;margin-bottom:8px">✓ E-commerce</div><div style="color:#555;font-size:13px;margin-bottom:16px">✓ Gerente dedicado</div><a href="#" style="display:block;text-align:center;background:#111;color:#fff;padding:12px;border-radius:10px;font-weight:600;text-decoration:none">Contratar</a></div></div></section>',
  },

  // ── Contato ───────────────────────────────────────────────────────────────
  {
    id: 'cta', label: 'Chamada para Ação', category: '📧 Contato',
    content: '<section style="padding:70px 40px;background:linear-gradient(135deg,#E8922A,#c77a1e);text-align:center;font-family:sans-serif"><h2 style="color:#000;font-size:36px;font-weight:900;margin:0 0 14px">Pronto para Começar?</h2><p style="color:#000;font-size:16px;opacity:0.8;margin:0 0 28px">Orçamento gratuito em 24 horas. Sem compromisso.</p><div style="display:flex;gap:14px;justify-content:center;flex-wrap:wrap"><a href="#" style="display:inline-block;background:#000;color:#fff;padding:14px 36px;border-radius:50px;font-weight:700;text-decoration:none">Falar Agora</a><a href="#" style="display:inline-block;background:transparent;color:#000;padding:14px 36px;border-radius:50px;font-weight:700;text-decoration:none;border:2px solid #000">Ver Portfólio</a></div></section>',
  },
  {
    id: 'formulario', label: 'Formulário de Contato', category: '📧 Contato',
    content: '<section style="padding:60px 40px;background:#fff;font-family:sans-serif"><div style="max-width:560px;margin:0 auto"><h2 style="color:#111;font-size:32px;font-weight:800;text-align:center;margin:0 0 36px">Entre em Contato</h2><form style="display:flex;flex-direction:column;gap:14px"><input type="text" placeholder="Seu nome" style="padding:12px 16px;border:1px solid #e0e0e0;border-radius:10px;font-size:15px;outline:none"><input type="email" placeholder="seu@email.com" style="padding:12px 16px;border:1px solid #e0e0e0;border-radius:10px;font-size:15px;outline:none"><input type="text" placeholder="Assunto" style="padding:12px 16px;border:1px solid #e0e0e0;border-radius:10px;font-size:15px;outline:none"><textarea placeholder="Sua mensagem..." rows="4" style="padding:12px 16px;border:1px solid #e0e0e0;border-radius:10px;font-size:15px;outline:none;resize:vertical"></textarea><button type="submit" style="background:#E8922A;color:#000;padding:14px;border-radius:10px;font-weight:700;font-size:15px;border:none;cursor:pointer">Enviar Mensagem</button></form></div></section>',
  },

  // ── Stats ─────────────────────────────────────────────────────────────────
  {
    id: 'stats', label: 'Números / Stats', category: '🔢 Estatísticas',
    content: '<section style="padding:50px 40px;background:#111;font-family:sans-serif"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:20px;max-width:800px;margin:0 auto;text-align:center"><div><div style="color:#E8922A;font-size:44px;font-weight:900">500+</div><div style="color:#888;font-size:13px;margin-top:6px">Projetos entregues</div></div><div><div style="color:#E8922A;font-size:44px;font-weight:900">98%</div><div style="color:#888;font-size:13px;margin-top:6px">Satisfação</div></div><div><div style="color:#E8922A;font-size:44px;font-weight:900">10+</div><div style="color:#888;font-size:13px;margin-top:6px">Anos</div></div><div><div style="color:#E8922A;font-size:44px;font-weight:900">24/7</div><div style="color:#888;font-size:13px;margin-top:6px">Suporte</div></div></div></section>',
  },

  // ── Rodapé ────────────────────────────────────────────────────────────────
  {
    id: 'footer-simples', label: 'Rodapé Simples', category: '🦶 Rodapé',
    content: '<footer style="background:#111;padding:32px 40px;text-align:center;font-family:sans-serif"><div style="color:#E8922A;font-size:20px;font-weight:800;margin-bottom:14px">Sua Empresa</div><div style="display:flex;justify-content:center;gap:20px;flex-wrap:wrap;margin-bottom:20px"><a href="#" style="color:#888;text-decoration:none;font-size:13px">Início</a><a href="#" style="color:#888;text-decoration:none;font-size:13px">Serviços</a><a href="#" style="color:#888;text-decoration:none;font-size:13px">Sobre</a><a href="#" style="color:#888;text-decoration:none;font-size:13px">Contato</a></div><p style="color:#555;font-size:12px;margin:0">© 2025 Sua Empresa. Todos os direitos reservados.</p></footer>',
  },

  // ── Elementos ─────────────────────────────────────────────────────────────
  {
    id: 'botao-laranja', label: 'Botão Principal', category: '🧩 Elementos',
    content: '<div style="padding:20px;font-family:sans-serif"><a href="#" style="display:inline-block;background:#E8922A;color:#000;padding:14px 32px;border-radius:10px;font-weight:700;font-size:15px;text-decoration:none">Botão de Ação</a></div>',
  },
  {
    id: 'botao-dark', label: 'Botão Escuro', category: '🧩 Elementos',
    content: '<div style="padding:20px;font-family:sans-serif"><a href="#" style="display:inline-block;background:#111;color:#fff;padding:14px 32px;border-radius:10px;font-weight:700;font-size:15px;text-decoration:none">Botão Secundário</a></div>',
  },
  {
    id: 'titulo-secao', label: 'Título de Seção', category: '🧩 Elementos',
    content: '<div style="padding:40px 40px 0;text-align:center;font-family:sans-serif"><p style="color:#E8922A;font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;margin:0 0 10px">Subtítulo</p><h2 style="color:#111;font-size:36px;font-weight:800;margin:0 0 12px">Título da Seção</h2><p style="color:#666;font-size:16px;max-width:500px;margin:0 auto">Descrição breve da seção com informações relevantes.</p></div>',
  },
  {
    id: 'alerta', label: 'Caixa de Alerta', category: '🧩 Elementos',
    content: '<div style="margin:16px 40px;padding:14px 18px;background:#fff3cd;border-left:4px solid #E8922A;border-radius:8px;font-family:sans-serif"><strong style="color:#856404">⚠️ Atenção:</strong> <span style="color:#533f03">Insira aqui uma mensagem importante.</span></div>',
  },
  {
    id: 'divisor', label: 'Divisor', category: '🧩 Elementos',
    content: '<div style="padding:24px 40px"><div style="height:1px;background:linear-gradient(90deg,transparent,#E8922A66,transparent)"></div></div>',
  },
]
